import * as shell from "shelljs";

shell.echo(" ");
shell.echo(" ");
shell.echo(" ");
shell.echo(" ");
shell.echo(" ");
shell.echo(" ");
shell.echo(" ");
shell.echo(" ");
shell.echo(" ");
shell.echo(" ");
shell.echo(" ");
shell.echo(" ");
shell.echo(" ");
shell.echo(" ");
shell.echo(" ");
shell.echo(" ");
shell.echo(" ");
shell.echo("Headlinerr API is running.");